### ISSUE TITLE
"aka generate" hangs the console after it finishes

### ISSUE THREAD

**Issue by fgperianez** [ytbryan/aka-gem#18]
In Mac OS terminal at least, the console does not return to its working state after 'aka g' is used. 
<img width="367" alt="screen shot 2015-10-22 at 10 33 07" src="https://cloud.githubusercontent.com/assets/4253658/10660670/da85f812-78a8-11e5-95b2-c180c8e192f2.png">

I guess this comes from the line 
    
    system("kill -SIGUSR1 #{Process.ppid}")
    
in aka.rb - reload_dot_file. 
What is the reason for not using 'source dotfile' ?

**Comment by ytbryan** [comment]
> In Mac OS terminal at least, the console does not return to its working state after 'aka g' is used.

For your error, did you run `aka setup` after installing the gem? 

For bash, I think "source path_to_dotfile" does not reload the current shell when it is executed from system().

**Comment by fgperianez** [comment]
I could not finish the setup because I needed the dotfile to be .profile and this is not an option. 
If I run the setup and edit the \.aka\.config to point to .profile then everything works fine. 
Maybe we could add a 4th option to select .profile as the dotfile ?

**Comment by ytbryan** [comment]
> I could not finish the setup because I needed the dotfile to be .profile and this is not an option. 

You can actually call `aka init --dotfile "path_to_dotfile"` to set the path of the dotfile in .config

> Maybe we could add a 4th option to select .profile as the dotfile ?

ok.

**Comment by fgperianez** [comment]
Yes, selecting any option and calling init afterwards worked :)

Thanks for the help. 

Will you add the .profile option or should I open a pull request ?

**Comment by ytbryan** [comment]
:) No problem. Looking forward to your PR. https://github.com/ytbryan/aka-gem/pulls
